// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AtomButton: typeof import('./components/Atom/Button.vue')['default']
    AtomCard: typeof import('./components/Atom/Card.vue')['default']
    AtomInput: typeof import('./components/Atom/Input.vue')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OrganismFooter: typeof import('./components/Organism/Footer.vue')['default']
  }
}

export { }
